stages:
  -build
  -test

build:
  stage: build
  script: make
  artifacts:
    paths:
      - target/
    expire_in: 24 hours

# These jobs run in parallel as part of the test stage

unit:
  stage: test
  script: sbt test

integration:
  stage: test
  before_script:
    - git submodule init
    - git submodule update
  script: ./run_all_tests.py