before_script:
  - sbt sbt-version
  - git submodule init
  - git submodule update

build:
  script:
    - make

test:
  script:
    # Execute your project's tests
    - make # Need to make in order to generate antlr files
    - sbt clean test
    - ./run_all_tests.py
