#!/bin/bash
# Do *not* change the name or location of this script
# Compiles a WACC file to ARM11 assembly

DIR=$(dirname $0)

SOURCE_PATH=$1
SOURCE_FILE=$(basename ${SOURCE_PATH})

# Assembly file is created in current directory
OUT=${SOURCE_FILE%wacc}s

# Compiler to run
COMPILER=wacc.Compiler

# Flag for printing to standard output instead of a file
if [[ $2 = "--stdout" ]]; then
    OUT=/dev/stdout
elif [[ $2 = "--interactive" ]]; then
    COMPILER=wacc.ICompiler
fi

# TODO: remove assembly file in case of compilation errors
scala -cp ${DIR}/target/scala-2.11/wacc_27_2.11-1.0.jar:${DIR}/lib/antlr-4.5.3-complete.jar \
          ${COMPILER} < ${SOURCE_PATH} > ${OUT}
exit $?