#!/bin/bash

READLINK="readlink"

if [[ "$OSTYPE" == "darwin"* ]]; then
    READLINK="greadlink"
fi

#echo running the ANTLR TestRig grammar tool
DIR=$(dirname $0)
CP=$DIR"/bin:"$DIR"/lib/antlr-4.5.3-complete.jar"
java -cp $CP org.antlr.v4.gui.TestRig antlr.WACC program $@
